import { supabase } from "./supabase";

export type OrderRow={id:string;order_number:string;status:string;project_id:string;budget_id:string|null;customer_name:string|null;project_name:string|null;total_amount:number};
export type OrderItem={id:string;order_id:string;description:string;material:string|null;quantity:number;length_cm:number|null;width_cm:number|null;area_m2:number|null;unit_price:number;total_price:number;status:string};
export type Measurement={id:string;order_id:string;project_id:string;scope:string;status:string;measured_at:string;notes:string|null};
export type ProductionTask={id:string;order_id:string;order_item_id:string|null;task_type:string;status:string;priority:number;assigned_to:string|null;started_at:string|null;completed_at:string|null;notes:string|null};
export type Delivery={id:string;order_id:string;type:string;scheduled_date:string|null;status:string;notes:string|null};

async function ctx(){if(!supabase)return null;const {data:u}=await supabase.auth.getUser();if(!u.user)return null;const {data,error}=await supabase.from("organization_members").select("organization_id").eq("user_id",u.user.id).eq("active",true).limit(1).maybeSingle();if(error)throw error;return data?{userId:u.user.id,organizationId:data.organization_id}:null}

export async function loadOrders(){if(!supabase)return[] as OrderRow[];const {data,error}=await supabase.from("dashboard_order_summary").select("id,order_number,status,project_id,budget_id,customer_name,project_name,total_amount").order("created_at",{ascending:false}).limit(200);if(error)throw error;return(data??[]).map(r=>({...r,total_amount:Number(r.total_amount??0)})) as OrderRow[]}
export async function loadOrderItems(orderId:string){if(!supabase)return[] as OrderItem[];const {data,error}=await supabase.from("order_items").select("id,order_id,description,material,quantity,length_cm,width_cm,area_m2,unit_price,total_price,status").eq("order_id",orderId).order("created_at");if(error)throw error;return(data??[]).map(r=>({...r,quantity:Number(r.quantity),unit_price:Number(r.unit_price),total_price:Number(r.total_price),length_cm:r.length_cm==null?null:Number(r.length_cm),width_cm:r.width_cm==null?null:Number(r.width_cm),area_m2:r.area_m2==null?null:Number(r.area_m2)})) as OrderItem[]}
export async function loadMeasurements(orderId?:string){if(!supabase)return[] as Measurement[];let q=supabase.from("measurements").select("id,order_id,project_id,scope,status,measured_at,notes").order("measured_at",{ascending:false}).limit(200);if(orderId)q=q.eq("order_id",orderId);const {data,error}=await q;if(error)throw error;return(data??[]) as Measurement[]}
export async function loadProductionTasks(orderId?:string){if(!supabase)return[] as ProductionTask[];let q=supabase.from("production_tasks").select("id,order_id,order_item_id,task_type,status,priority,assigned_to,started_at,completed_at,notes").order("priority").limit(300);if(orderId)q=q.eq("order_id",orderId);const {data,error}=await q;if(error)throw error;return(data??[]) as ProductionTask[]}
export async function loadDeliveries(orderId?:string){if(!supabase)return[] as Delivery[];let q=supabase.from("deliveries").select("id,order_id,type,scheduled_date,status,notes").order("scheduled_date").limit(200);if(orderId)q=q.eq("order_id",orderId);const {data,error}=await q;if(error)throw error;return(data??[]) as Delivery[]}

export async function createMeasurement(input:{order_id:string;project_id:string;scope:string;status?:string;measured_at?:string;notes?:string|null}){if(!supabase)throw new Error("Supabase não configurado.");const c=await ctx();if(!c)throw new Error("Usuário sem empresa vinculada.");const {data,error}=await supabase.from("measurements").insert({...input,organization_id:c.organizationId,measured_by:c.userId,status:input.status??"pending",measured_at:input.measured_at??new Date().toISOString()}).select().single();if(error)throw error;return data}
export async function createProductionTask(input:{order_id:string;order_item_id?:string|null;task_type:string;priority?:number;notes?:string|null}){if(!supabase)throw new Error("Supabase não configurado.");const c=await ctx();if(!c)throw new Error("Usuário sem empresa vinculada.");const {data,error}=await supabase.from("production_tasks").insert({...input,organization_id:c.organizationId,status:"pending",priority:input.priority??50}).select().single();if(error)throw error;return data}
export async function createDelivery(input:{order_id:string;type:string;scheduled_date?:string|null;notes?:string|null}){if(!supabase)throw new Error("Supabase não configurado.");const c=await ctx();if(!c)throw new Error("Usuário sem empresa vinculada.");const {data,error}=await supabase.from("deliveries").insert({...input,organization_id:c.organizationId,status:"scheduled"}).select().single();if(error)throw error;return data}
export async function transitionOrder(orderId:string,status:string){if(!supabase)throw new Error("Supabase não configurado.");const c=await ctx();if(!c)throw new Error("Usuário sem empresa vinculada.");const {data:old,error:oe}=await supabase.from("orders").select("status").eq("id",orderId).single();if(oe)throw oe;const {data,error}=await supabase.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",orderId).select().single();if(error)throw error;await supabase.from("order_events").insert({organization_id:c.organizationId,order_id:orderId,event_type:"status_changed",from_status:old.status,to_status:status,actor_user_id:c.userId,metadata:{}});return data}
