import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, Plus, Users, X } from "lucide-react";
import { createBudget, createCustomer, createProject, getCommercialContext, loadBudgets, loadCustomers, loadProjects, type Budget, type Customer, type Project } from "./lib/commercial";

type Props={module:string;search:string;onToast:(message:string)=>void};

export default function CommercialPanel({module,search,onToast}:Props){
 const [customers,setCustomers]=useState<Customer[]>([]);
 const [projects,setProjects]=useState<Project[]>([]);
 const [budgets,setBudgets]=useState<Budget[]>([]);
 const [ctx,setCtx]=useState<{userId:string;organizationId:string}|null>(null);
 const [modal,setModal]=useState<"customer"|"project"|"budget"|null>(null);
 const [error,setError]=useState("");
 const load=async()=>{try{const c=await getCommercialContext();setCtx(c);if(c){const [cs,ps,bs]=await Promise.all([loadCustomers(),loadProjects(),loadBudgets()]);setCustomers(cs);setProjects(ps);setBudgets(bs);}}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os dados.");}};
 useEffect(()=>{load()},[]);
 const q=search.toLowerCase();
 const filteredCustomers=useMemo(()=>customers.filter(c=>[c.name,c.trade_name??"",c.phone??""].some(v=>v.toLowerCase().includes(q))),[customers,q]);
 const filteredProjects=useMemo(()=>projects.filter(p=>[p.name,p.city??"",p.state??""].some(v=>v.toLowerCase().includes(q))),[projects,q]);
 const filteredBudgets=useMemo(()=>budgets.filter(b=>[b.code,b.customer_name??"",b.project_name??"",b.status].some(v=>v.toLowerCase().includes(q))),[budgets,q]);
 async function refresh(){const [cs,ps,bs]=await Promise.all([loadCustomers(),loadProjects(),loadBudgets()]);setCustomers(cs);setProjects(ps);setBudgets(bs);}
 if(module==="Clientes e obras") return <section className="module-stack"><div className="module-actions"><div><span className="eyebrow">CADASTRO</span><h2>Clientes e obras</h2></div><div><button className="secondary" onClick={()=>setModal("project")}><Building2 size={15}/>Nova obra</button><button className="primary" onClick={()=>setModal("customer")}><Plus size={15}/>Novo cliente</button></div></div>{error&&<div className="data-warning">{error}</div>}<div className="entity-grid">{filteredCustomers.map(c=><article className="entity-card" key={c.id}><div className="entity-icon"><Users size={18}/></div><div><strong>{c.name}</strong><span>{c.phone||c.whatsapp||"Contato não informado"}</span><small>{projects.filter(p=>p.customer_id===c.id).length} obra(s)</small></div></article>)}</div><div className="panel"><div className="panel-head"><div><span className="eyebrow">OBRAS</span><h2>Obras cadastradas</h2></div></div><div className="table">{filteredProjects.map(p=><div className="row" key={p.id}><div><strong>{p.name}</strong><span>{customers.find(c=>c.id===p.customer_id)?.name??"Cliente"}</span></div><span>{p.city?(p.city+(p.state?" · "+p.state:"")):"Endereço não informado"}</span><span className="status">{p.status}</span><strong>Obra</strong></div>)}</div></div>{modal==="customer"&&<CustomerModal ctx={ctx} close={()=>setModal(null)} saved={async()=>{setModal(null);await refresh();onToast("Cliente cadastrado.")}}/>}{modal==="project"&&<ProjectModal ctx={ctx} customers={customers} close={()=>setModal(null)} saved={async()=>{setModal(null);await refresh();onToast("Obra cadastrada.")}}/>}</section>;
 if(module==="Orçamentos") return <section className="module-stack"><div className="module-actions"><div><span className="eyebrow">COMERCIAL</span><h2>Orçamentos</h2></div><button className="primary" onClick={()=>setModal("budget")}><Plus size={15}/>Novo orçamento</button></div>{error&&<div className="data-warning">{error}</div>}<div className="panel"><div className="table">{filteredBudgets.map(b=><div className="row" key={b.id}><div><strong>{b.code} · v{b.version}</strong><span>{b.customer_name??"Cliente"}</span></div><span>{b.project_name??"Obra"}</span><span className="status">{b.status}</span><strong>{b.total_amount.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div>)}</div></div>{modal==="budget"&&<BudgetModal ctx={ctx} customers={customers} projects={projects} close={()=>setModal(null)} saved={async()=>{setModal(null);await refresh();onToast("Orçamento criado.")}}/>}</section>;
 return <section className="module-stack"><div className="module-actions"><div><span className="eyebrow">OPERAÇÃO</span><h2>Pedidos</h2></div></div><div className="panel"><p className="module-copy">Os pedidos continuam ligados à obra e ao orçamento aprovados. O próximo passo é liberar a pasta digital e o fluxo técnico.</p></div></section>;
}

function CustomerModal({ctx,close,saved}:{ctx:{userId:string;organizationId:string}|null;close:()=>void;saved:()=>void}){const [name,setName]=useState("");const [phone,setPhone]=useState("");const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();if(!ctx){setError("Nenhuma empresa vinculada ao usuário.");return}try{await createCustomer({name,trade_name:"",document:"",email:"",phone,whatsapp:phone},ctx);saved()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}}return <div className="overlay" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">CADASTRO</span><h2>Novo cliente</h2></div><button type="button" className="close" onClick={close}><X/></button></div><label>Nome<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} /></label>{error&&<div className="data-warning">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Salvar cliente</button></div></form></div>}

function ProjectModal({ctx,customers,close,saved}:{ctx:{userId:string;organizationId:string}|null;customers:Customer[];close:()=>void;saved:()=>void}){const [customer_id,setCustomer]=useState(customers[0]?.id??"");const [name,setName]=useState("");const [city,setCity]=useState("");const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();if(!ctx){setError("Nenhuma empresa vinculada ao usuário.");return}try{await createProject({customer_id,name,project_type:"Residencial",city,state:"PE",postal_code:"",notes:""},ctx);saved()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}}return <div className="overlay" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">OBRA</span><h2>Nova obra</h2></div><button type="button" className="close" onClick={close}><X/></button></div><label>Cliente<select value={customer_id} onChange={e=>setCustomer(e.target.value)}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Nome da obra<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>Cidade<input value={city} onChange={e=>setCity(e.target.value)} /></label>{error&&<div className="data-warning">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Salvar obra</button></div></form></div>}

function BudgetModal({ctx,customers,projects,close,saved}:{ctx:{userId:string;organizationId:string}|null;customers:Customer[];projects:Project[];close:()=>void;saved:()=>void}){const [customer_id,setCustomer]=useState(customers[0]?.id??"");const [project_id,setProject]=useState(projects[0]?.id??"");const [code,setCode]=useState("");const [error,setError]=useState("");const available=projects.filter(p=>p.customer_id===customer_id);useEffect(()=>{if(!available.some(p=>p.id===project_id))setProject(available[0]?.id??"")},[customer_id]);async function submit(e:FormEvent){e.preventDefault();if(!ctx){setError("Nenhuma empresa vinculada ao usuário.");return}if(!project_id){setError("Cadastre uma obra antes de criar o orçamento.");return}try{await createBudget({customer_id,project_id,code,valid_until:null},ctx);saved()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}}return <div className="overlay" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">COMERCIAL</span><h2>Novo orçamento</h2></div><button type="button" className="close" onClick={close}><X/></button></div><label>Cliente<select value={customer_id} onChange={e=>setCustomer(e.target.value)}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Obra<select value={project_id} onChange={e=>setProject(e.target.value)}>{available.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Código<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="ORC-0001"/></label>{error&&<div className="data-warning">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Criar orçamento</button></div></form></div>}
